services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    restart: always
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - gatus-data:/data
    env_file:
      - .env
    networks:
      - web

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
    networks:
      - web

networks:
  web:

volumes:
  gatus-data:
  caddy-data: