storage:
  type: sqlite
  path: /data/data.db

alerting:
  custom:
    url: "https://chat.opentechstrategies.com/api/v1/messages"
    method: POST
    headers:
      Content-Type: "application/x-www-form-urlencoded"
      Authorization: "Basic ${ZULIP_BASIC_AUTH}"
    body: "type=stream&to=PDC&topic=monitoring&content=ALERT:%20[ENDPOINT_NAME]%20status%20changed.%20Check%20the%20status%20page."

endpoints:
  - name: PDC main site
    url: "https://philanthropydatacommons.org"
    interval: 600s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        description: "Healthcheck failed for philanthropydatacommons.org"
        send-on-resolved: true    

  - name: PDC API
    url: "https://api.philanthropydatacommons.org"
    interval: 600s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        description: "Healthcheck failed for api.philanthropydatacommons.org"
        send-on-resolved: true      

  - name: PDC App
    url: "https://app.philanthropydatacommons.org"
    interval: 600s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        description: "Healthcheck failed for app.philanthropydatacommons.org"
        send-on-resolved: true          

  - name: PDC Admin
    url: "https://admin.philanthropydatacommons.org"
    interval: 600s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        description: "Healthcheck failed for admin.philanthropydatacommons.org"
        send-on-resolved: true    

  - name: PDC Exchange
    url: "https://exchange.philanthropydatacommons.org"
    interval: 600s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        description: "Healthcheck failed for exchange.philanthropydatacommons.org"
        send-on-resolved: true

  - name: PDC Keycloak
    url: "https://auth.philanthropydatacommons.org"
    interval: 600s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        description: "Healthcheck failed for auth.philanthropydatacommons.org"
        send-on-resolved: true   

  - name: PDC Keycloak test
    url: "https://auth.test.philanthropydatacommons.org"
    interval: 600s
    conditions:
      - "[STATUS] == 200"
    alerts:
      - type: custom
        description: "Healthcheck failed for auth.test.philanthropydatacommons.org"
        send-on-resolved: true

  - name: PDC utilities server
    url: "icmp://pdc-utilities.opentechstrategies.com"
    interval: 600s
    conditions:
     - "[CONNECTED] == true"
    alerts:
      - type: custom
        description: "Healthcheck failed for pdc-utilties.opentechstrategies.com"
        send-on-resolved: true              